
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DESTROY_PRODUCT = 'DESTROY_PRODUCT'
export const LOAD_PRODUCT = 'LOAD_PRODUCT'
export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_FIELD = 'UPDATE_PRODUCT_FIELD'
