
export const LOAD_OPTIONS = 'LOAD_OPTIONS'
export const LOAD_OPTIONS_TEMPLATES = 'LOAD_OPTIONS_TEMPLATES'
export const LOAD_OPTIONS_GROUPS = 'LOAD_OPTIONS_GROUPS'
export const LOAD_OPTIONS_FIELDS = 'LOAD_OPTIONS_FIELDS'
