
export const CREATE_PRODUCT_TEMPLATE = 'CREATE_PRODUCT_TEMPLATE'
export const DESTROY_PRODUCT_TEMPLATE = 'DESTROY_PRODUCT_TEMPLATE'
export const FETCH_PRODUCT_TEMPLATE_LIST = 'FETCH_PRODUCT_TEMPLATE_LIST'
export const UPDATE_PRODUCT_TEMPLATE = 'UPDATE_PRODUCT_TEMPLATE'
